/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazJuego;
import java.awt.Component;
import java.awt.Image;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author monic
 */
public class escogerPersonajes_Juego extends javax.swing.JFrame {
    /**
     * Creates new form escogerPersonajes_Juego
     
     */
    public escogerPersonajes_Juego() {
       
    }
    
    public boolean creceNivel(String tipoGuerrero){
        if(tipoGuerrero.equalsIgnoreCase("Guerrero de Contacto") || tipoGuerrero.equalsIgnoreCase("Guerrero de mediano alcance") || tipoGuerrero.equalsIgnoreCase("Guerrero aéreo")){
            return true;
        }else{
            return false;
        }
    }
    
    public void tabla(){
        
     }
    
    class CellRenderer implements TableCellRenderer {
 
        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
 
            TableColumn tb = table_Personajes.getColumn("Imagen");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
 
            table_Personajes.setRowHeight(60);
 
            return (Component) value;
        }

    }
    
    public void subirNivel(){
        
    }
    
    public boolean getValues(){
        return true;
    }        
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Fondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Personajes = new javax.swing.JTable();
        btn_Escoger = new javax.swing.JButton();
        lbl_userLevel = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escoger personajes para jugar");
        setMinimumSize(new java.awt.Dimension(755, 456));
        setResizable(false);
        setSize(new java.awt.Dimension(755, 456));

        panel_Fondo.setLayout(null);

        table_Personajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Imagen", "Ataque", "Vida", "Tipo Guerrero", "Campos", "Escogido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Personajes);

        panel_Fondo.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 740, 330);

        btn_Escoger.setBackground(new java.awt.Color(0, 0, 0));
        btn_Escoger.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        btn_Escoger.setForeground(new java.awt.Color(102, 0, 102));
        btn_Escoger.setText("Escoger personajes");
        btn_Escoger.setOpaque(false);
        btn_Escoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EscogerActionPerformed(evt);
            }
        });
        panel_Fondo.add(btn_Escoger);
        btn_Escoger.setBounds(250, 390, 260, 40);

        lbl_userLevel.setBackground(new java.awt.Color(0, 0, 0));
        lbl_userLevel.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_userLevel.setForeground(new java.awt.Color(102, 0, 102));
        lbl_userLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        lbl_userLevel.setOpaque(true);
        panel_Fondo.add(lbl_userLevel);
        lbl_userLevel.setBounds(580, 10, 160, 30);

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/herenciaAlTrono/imagenes_Juego/fondo_Juego.jpg"))); // NOI18N
        panel_Fondo.add(lbl_Fondo);
        lbl_Fondo.setBounds(-260, -150, 0, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EscogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EscogerActionPerformed

    }//GEN-LAST:event_btn_EscogerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Escoger;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_userLevel;
    private javax.swing.JPanel panel_Fondo;
    private javax.swing.JTable table_Personajes;
    // End of variables declaration//GEN-END:variables
}
