package CreacionPersonajes.Interfaces;
import CreacionPersonajes.Logica.*;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author monic
 */
public class ingresarGear extends javax.swing.JFrame {
    private ArrayList<Gear> gears;
    String imageDir = "src/main/java/Juego/ImagenesJuego/";
    
    public ingresarGear() {
        initComponents();
        addTableHeader();
        Object valor=gears=(ArrayList<Gear>) FileManager.readObject("src/main/java/CreacionPersonajes/Archivos/gears.juego");  
        if(valor!=null){
            gears=(ArrayList<Gear>) FileManager.readObject("src/main/java/CreacionPersonajes/Archivos/gears.juego");  
       }else{
           gears=new ArrayList<>();
       }
        generarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Fondo = new javax.swing.JPanel();
        lbl_Titulo0 = new javax.swing.JLabel();
        txt_Ola = new javax.swing.JTextField();
        lbl_NivelPersonaje = new javax.swing.JLabel();
        lbl_AccionPersonaje = new javax.swing.JLabel();
        txt_Danno = new javax.swing.JTextField();
        txt_NombreImagen = new javax.swing.JTextField();
        btn_ImagenApariencia = new javax.swing.JButton();
        lbl_ImagenApariencia = new javax.swing.JLabel();
        btn_Ingresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Gears = new javax.swing.JTable();
        lbl_Usuario1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        lbl_NivelPersonaje1 = new javax.swing.JLabel();
        txt_Rango = new javax.swing.JTextField();
        lbl_NivelPersonaje2 = new javax.swing.JLabel();
        lbl_NivelPersonaje3 = new javax.swing.JLabel();
        txt_Nivel = new javax.swing.JTextField();
        combo_Tipos = new javax.swing.JComboBox<>();
        fondo_Juego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar gear");
        setResizable(false);
        setSize(new java.awt.Dimension(755, 456));

        panel_Fondo.setMaximumSize(new java.awt.Dimension(755, 456));
        panel_Fondo.setMinimumSize(new java.awt.Dimension(755, 456));
        panel_Fondo.setLayout(null);

        lbl_Titulo0.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Titulo0.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbl_Titulo0.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Titulo0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Titulo0.setText("Ingresar gears");
        lbl_Titulo0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_Titulo0.setOpaque(true);
        panel_Fondo.add(lbl_Titulo0);
        lbl_Titulo0.setBounds(130, 10, 500, 50);

        txt_Ola.setBackground(new java.awt.Color(102, 0, 102));
        txt_Ola.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        txt_Ola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OlaActionPerformed(evt);
            }
        });
        panel_Fondo.add(txt_Ola);
        txt_Ola.setBounds(590, 170, 170, 30);

        lbl_NivelPersonaje.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NivelPersonaje.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_NivelPersonaje.setForeground(new java.awt.Color(102, 0, 102));
        lbl_NivelPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NivelPersonaje.setText("Activa:");
        lbl_NivelPersonaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_NivelPersonaje.setOpaque(true);
        panel_Fondo.add(lbl_NivelPersonaje);
        lbl_NivelPersonaje.setBounds(410, 220, 160, 30);

        lbl_AccionPersonaje.setBackground(new java.awt.Color(255, 255, 255));
        lbl_AccionPersonaje.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_AccionPersonaje.setForeground(new java.awt.Color(102, 0, 102));
        lbl_AccionPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_AccionPersonaje.setText("Rango:");
        lbl_AccionPersonaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_AccionPersonaje.setOpaque(true);
        panel_Fondo.add(lbl_AccionPersonaje);
        lbl_AccionPersonaje.setBounds(410, 70, 160, 30);

        txt_Danno.setBackground(new java.awt.Color(102, 0, 102));
        txt_Danno.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        txt_Danno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DannoActionPerformed(evt);
            }
        });
        panel_Fondo.add(txt_Danno);
        txt_Danno.setBounds(220, 120, 180, 30);

        txt_NombreImagen.setBackground(new java.awt.Color(102, 0, 102));
        txt_NombreImagen.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        panel_Fondo.add(txt_NombreImagen);
        txt_NombreImagen.setBounds(70, 260, 350, 30);

        btn_ImagenApariencia.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        btn_ImagenApariencia.setForeground(new java.awt.Color(102, 0, 102));
        btn_ImagenApariencia.setText("Seleccionar imagen de apariencia");
        btn_ImagenApariencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImagenAparienciaActionPerformed(evt);
            }
        });
        panel_Fondo.add(btn_ImagenApariencia);
        btn_ImagenApariencia.setBounds(70, 300, 350, 50);

        lbl_ImagenApariencia.setToolTipText("Imagen enemigo");
        lbl_ImagenApariencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_Fondo.add(lbl_ImagenApariencia);
        lbl_ImagenApariencia.setBounds(70, 160, 100, 90);

        btn_Ingresar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Ingresar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btn_Ingresar.setForeground(new java.awt.Color(102, 0, 102));
        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        panel_Fondo.add(btn_Ingresar);
        btn_Ingresar.setBounds(520, 310, 150, 40);

        table_Gears.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_Gears.setGridColor(new java.awt.Color(102, 0, 102));
        jScrollPane2.setViewportView(table_Gears);

        panel_Fondo.add(jScrollPane2);
        jScrollPane2.setBounds(30, 360, 720, 130);

        lbl_Usuario1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Usuario1.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_Usuario1.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Usuario1.setText("Nombre:");
        lbl_Usuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_Usuario1.setOpaque(true);
        panel_Fondo.add(lbl_Usuario1);
        lbl_Usuario1.setBounds(70, 70, 140, 30);

        txt_Nombre.setBackground(new java.awt.Color(102, 0, 102));
        txt_Nombre.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        panel_Fondo.add(txt_Nombre);
        txt_Nombre.setBounds(220, 70, 180, 30);

        lbl_NivelPersonaje1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NivelPersonaje1.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_NivelPersonaje1.setForeground(new java.awt.Color(102, 0, 102));
        lbl_NivelPersonaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NivelPersonaje1.setText("Daño:");
        lbl_NivelPersonaje1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_NivelPersonaje1.setOpaque(true);
        panel_Fondo.add(lbl_NivelPersonaje1);
        lbl_NivelPersonaje1.setBounds(70, 120, 140, 30);

        txt_Rango.setBackground(new java.awt.Color(102, 0, 102));
        txt_Rango.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        panel_Fondo.add(txt_Rango);
        txt_Rango.setBounds(590, 70, 170, 30);

        lbl_NivelPersonaje2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NivelPersonaje2.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_NivelPersonaje2.setForeground(new java.awt.Color(102, 0, 102));
        lbl_NivelPersonaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NivelPersonaje2.setText("Nivel:");
        lbl_NivelPersonaje2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_NivelPersonaje2.setOpaque(true);
        panel_Fondo.add(lbl_NivelPersonaje2);
        lbl_NivelPersonaje2.setBounds(410, 120, 160, 30);

        lbl_NivelPersonaje3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NivelPersonaje3.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        lbl_NivelPersonaje3.setForeground(new java.awt.Color(102, 0, 102));
        lbl_NivelPersonaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NivelPersonaje3.setText("Ola expansiva:");
        lbl_NivelPersonaje3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_NivelPersonaje3.setOpaque(true);
        panel_Fondo.add(lbl_NivelPersonaje3);
        lbl_NivelPersonaje3.setBounds(410, 170, 160, 30);

        txt_Nivel.setBackground(new java.awt.Color(102, 0, 102));
        txt_Nivel.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        panel_Fondo.add(txt_Nivel);
        txt_Nivel.setBounds(590, 120, 170, 30);

        combo_Tipos.setBackground(new java.awt.Color(0, 0, 0));
        combo_Tipos.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        combo_Tipos.setForeground(new java.awt.Color(102, 0, 102));
        combo_Tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        combo_Tipos.setSelectedIndex(-1);
        combo_Tipos.setToolTipText("Tipo guerrero");
        combo_Tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_TiposActionPerformed(evt);
            }
        });
        panel_Fondo.add(combo_Tipos);
        combo_Tipos.setBounds(590, 220, 180, 30);

        fondo_Juego.setIcon(new javax.swing.ImageIcon("D:\\Documents\\GitHub\\creacionPersonajesGui\\src\\main\\java\\CreacionPersonajes\\Interfaces\\ImagenesCreacionPersonajes\\FondoPantallas.png")); // NOI18N
        panel_Fondo.add(fondo_Juego);
        fondo_Juego.setBounds(0, -20, 790, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("Ingresar personajes al juego (ADMIN)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DannoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DannoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DannoActionPerformed

    private void btn_ImagenAparienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImagenAparienciaActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & PNG Images", "png", "jpg", "jpeg");
        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            txt_NombreImagen.setText(chooser.getSelectedFile().getName());
            File selectedImageFile = chooser.getSelectedFile();
            String selectedImagePath = imageDir+selectedImageFile.getName();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            ImageIcon ii = new ImageIcon(selectedImagePath);
            //            Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lbl_ImagenApariencia.getWidth(), lbl_ImagenApariencia.getHeight(), Image.SCALE_SMOOTH);

            lbl_ImagenApariencia.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btn_ImagenAparienciaActionPerformed

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        // TODO add your handling code here:
       String nombreStr=txt_Nombre.getText();
       String dannoStr=txt_Danno.getText();
       String rangoStr=txt_Rango.getText();
       String nivelStr=txt_Nivel.getText();
       String olaEStr=txt_Ola.getText();
       String imageStr=imageDir+txt_NombreImagen.getText();
       int activobtn= combo_Tipos.getSelectedIndex();
       String activoStr= combo_Tipos.getItemAt(activobtn);
       boolean activo=false;
        
        if(!nombreStr.isBlank() && !dannoStr.isBlank() && !rangoStr.isBlank() 
           && !nivelStr.isBlank() && !olaEStr.isBlank() && !imageStr.isBlank() && !activoStr.isBlank()){
            int danno=Integer.parseInt(dannoStr);
            int rango=Integer.parseInt(rangoStr);
            int nivel=Integer.parseInt(nivelStr);
            int olaE=Integer.parseInt(olaEStr);
            if(activoStr=="Activo")
                activo=true;
            
            Gear gearItem=new Gear(nombreStr, rango, danno, nivel, olaE, imageStr,activo);
            gears.add(gearItem);
            FileManager.writeObject(gears,"src/main/java/CreacionPersonajes/Archivos/gears.juego");
            
            JLabel imageLabel = new JLabel();
            ImageIcon imageicon = new ImageIcon(imageDir+txt_NombreImagen.getText());
            Image img = imageicon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
            model.addRow(new Object[]{nombreStr,rango,danno,nivel,olaE,activoStr,imageLabel});
            limpiarFields();
            
        }else{
            JOptionPane.showMessageDialog(panel_Fondo,"Los campos están vacíos.","Atención",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_OlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OlaActionPerformed

    private void combo_TiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_TiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_TiposActionPerformed
    DefaultTableModel model;
    
//    byte imageJtable = new Byte(1024);
 
//Adding table headers
    public void addTableHeader() {
        model = (DefaultTableModel) table_Gears.getModel();
        Object[] newIdentifiers = new Object[]{"Nombre", "Rango", "Daño", "Nivel", "Ola expansiva", "Activo", "Imagen"};
        model.setColumnIdentifiers(newIdentifiers);
        table_Gears.setFillsViewportHeight(true);
        table_Gears.getColumn("Imagen").setCellRenderer(new CellRenderer());
 
    }

    class CellRenderer implements TableCellRenderer {
 
        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
 
            TableColumn tb = table_Gears.getColumn("Imagen");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
 
            table_Gears.setRowHeight(60); 
 
            return (Component) value;
        }
    }
    private void generarTabla(){
        for(int i=0;i<gears.size();i++){
            String nombre=gears.get(i).getgName();
            int rango=gears.get(i).getgRange();
            int danno=gears.get(i).getgRange();
            int nivel=gears.get(i).getgLevel();
            int olaE=gears.get(i).getgGearBLast();
            boolean activo=gears.get(i).isgActive();
            String imagenStr=gears.get(i).getgAppearanceURL();
            JLabel imageLabel = new JLabel();
            ImageIcon imageicon = new ImageIcon(imagenStr);
            Image img = imageicon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
            
            model.addRow(new Object[]{nombre,rango,danno,nivel,olaE,activo,imageLabel});
        }
  }
   
    private void limpiarFields() {
       lbl_ImagenApariencia.setIcon(new ImageIcon());
       txt_Nombre.setText("");
       txt_Danno.setText("");
       txt_Rango.setText("");
       txt_Nivel.setText("");
       txt_Ola.setText("");
       txt_NombreImagen.setText("");
       combo_Tipos.setSelectedIndex(-1);
       txt_NombreImagen.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresarApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresarApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresarApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresarApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ingresarGear frame = new ingresarGear();
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
                frame.pack();
                frame.setLocation(290, 50);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ImagenApariencia;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JComboBox<String> combo_Tipos;
    private javax.swing.JLabel fondo_Juego;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_AccionPersonaje;
    private javax.swing.JLabel lbl_ImagenApariencia;
    private javax.swing.JLabel lbl_NivelPersonaje;
    private javax.swing.JLabel lbl_NivelPersonaje1;
    private javax.swing.JLabel lbl_NivelPersonaje2;
    private javax.swing.JLabel lbl_NivelPersonaje3;
    private javax.swing.JLabel lbl_Titulo0;
    private javax.swing.JLabel lbl_Usuario1;
    private javax.swing.JPanel panel_Fondo;
    private javax.swing.JTable table_Gears;
    private javax.swing.JTextField txt_Danno;
    private javax.swing.JTextField txt_Nivel;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_NombreImagen;
    private javax.swing.JTextField txt_Ola;
    private javax.swing.JTextField txt_Rango;
    // End of variables declaration//GEN-END:variables
}
